name: Frontend_Pipeline

on:
  push:
    branches: ["main"]

jobs:
  Build_and_Deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: tap_of_think
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm install

      - name: Build static files
        run: |
          rm -rf .output
          npm run build

      - name: Deploy Application
        run: pm2 restart ecosystem.config.cjs
